### ISSUE TITLE
model目录下文件缺失

### ISSUE THREAD

**Issue by GuiHong01** [yutchina/MMDFND#1]
作者您好，很抱歉打扰您。我最近在学习您分享的项目代码时遇到了一些问题，希望您能提供一些帮助。是这样的，我在尝试复现代码过程中发现model目录下缺少了一些文件，您能分享一下吗？谢谢您！
![示例](https://github.com/user-attachments/assets/138b4ce8-2d1a-4436-a4fe-403915d2319b)

**Comment by yutchina** [comment]
你好 因为论文还没有正式发布 所以我还没有整理代码 根据你提出的问题我刚刚修改了代码 你可以进行再次尝试 后续我会发布贴上了领域标签的多模态数据集
