### ISSUE TITLE
标签预测均值

### ISSUE THREAD

**Issue by liaolea** [yutchina/MMDFND#2]
作者您好，最近在学习您的代码时发现这个text_label_pred_avg = text_label_pred_avg / 8，但是实际在过程中设置了9个域，为什么是除以8呢。我的疑惑出现在mmdfnd中forward函数涉及DPLE模块的代码。
![1726060048696](https://github.com/user-attachments/assets/6c0fba04-9878-429a-88a0-fc5d8f02a0f2)

**Comment by yutchina** [comment]
你好 因为我后面没有用到这个avg 所以就没有改 你如果需要用到这个avg 你可以更改为9

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月11日 21:08 |
| 收件人 | yutchina/MMDFND ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [yutchina/MMDFND] 标签预测均值 (Issue #2) |

作者您好，最近在学习您的代码时发现这个text_label_pred_avg = text_label_pred_avg / 8，但是实际在过程中设置了9个域，为什么是除以8呢。我的疑惑出现在mmdfnd中forward函数涉及DPLE模块的代码。
1726060048696.png (view on web)
