### ISSUE TITLE
关于CLIP余弦相似度计算和bert语言处理过后的语言特征与mae处理的图像特征结合

### ISSUE THREAD

**Issue by Scientist888-star** [yutchina/MMDFND#3]
您好！冒昧打扰，感谢您的文章和分享的代码，为我的研究提供指导，但是我在仔细阅读您的代码过后，有两个小问题想咨询：
1. 您的文章里面写道：“By utilizing the CLIP model’s encoder to encode both images and text, we obtain aligned image and text embeddings. These embeddings are then concatenated and fed into an MLP network to generate the multimodal representation. To address the ambiguity issues introduced by the classifier, we utilize the CLIP cosine similarity as a cross-modal similarity measure to weight the multimodal features.”，但是在代码（1）中没有体现，请问是在别的地方有进行计算吗？
2. 您代码里面将bert处理过的文本和mae处理过后的图像嵌入进行融合，但是您的文章中没有提及，您文章中写道经过bert处理过的文本和mae处理过后的图像嵌入以及CLIP融合之后三条通道单独输入到DPLE中。

![20241120214354](https://github.com/user-attachments/assets/a67385c6-42c5-464b-a9ca-27b157818d4f)

非常期待您的回复，谢谢！

**Comment by yutchina** [comment]
感谢你的疑问，与直接拼接相比，跨模态相似度能更好的结果，我需要一些时间仔细对比、选择服务器的代码。不过这个版本的代码结果是可以和论文中的结果相匹配的，你可以先使用这个代码进行尝试，这些细节问题不会造成方法描述以及实验结果的差异。

**Comment by Andrew-gx** [comment]
谢谢您的回复，我之后进行尝试，再次感谢！
