### ISSUE TITLE
code

### ISSUE THREAD

**Issue by LuoWeiCoder** [yutchina/MMDFND#4]
您好！冒昧打扰，感谢您的文章和分享的代码，为我的研究提供指导，但是我在仔细阅读您的代码之后，有个问题想咨询您：
在clip_data_pre.py中的这个 ：file_list = ['data/nonrumor_images/', 'data/rumor_images/']是指什么？是weibo数据集中的文件路径的列表吗？但是我似乎没有找到。

**Comment by yutchina** [comment]
file_list = ['data/nonrumor_images/', 'data/rumor_images/']是原始的weibo数据中的图片数据，处理好的文件已经在百度网盘中提供了，你可以直接用那个文件。

---- Replied Message ----
| From | ***@***.***> |
| Date | 11/21/2024 15:26 |
| To | yutchina/MMDFND ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [yutchina/MMDFND] code (Issue #4) |

您好！冒昧打扰，感谢您的文章和分享的代码，为我的研究提供指导，但是我在仔细阅读您的代码之后，有个问题想咨询您：
在clip_data_pre.py中的这个 ：file_list = ['data/nonrumor_images/', 'data/rumor_images/']是指什么？是weibo数据集中的文件路径的列表吗？但是我似乎没有找到。

**Comment by LuoWeiCoder** [comment]
是的，作者，我已经下载好了。但是我下载到本地了，如果要传输到服务器上会很慢，并且会有错误或者传输不全的情况。

**Comment by yutchina** [comment]
你可以打包后利用xftp上传，因为原始的图片其实也不小，不通过网盘的话你可以通过readme中的步骤进行操作
