### ISSUE TITLE
code

### ISSUE THREAD

**Issue by LuoWeiCoder** [yutchina/MMDFND#5]
作者您好！MAE ：从[“Masked Autoencoders： PyTorch 实现”](https://arxiv.org/abs/2111.06377)下载预训练的 MAE 模型并将所有文件移动到根目录中。这个是从GitHub上下载预训练的MAE模型吗？如果我下载好了是不是先得需要跑一遍MAE模型呢？这里我还是不太清楚，期待您的回复

**Comment by yutchina** [comment]
下载预训练好的就行 不需要重新训练

---- Replied Message ----
| From | ***@***.***> |
| Date | 11/26/2024 14:10 |
| To | yutchina/MMDFND ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [yutchina/MMDFND] code (Issue #5) |

作者您好！MAE ：从“Masked Autoencoders： PyTorch 实现”下载预训练的 MAE 模型并将所有文件移动到根目录中。这个是从GitHub上下载预训练的MAE模型吗？如果我下载好了是不是先得需要跑一遍MAE模型呢？这里我还是不太清楚，期待您的回复

**Comment by LuoWeiCoder** [comment]
GitHub上找一个去下载就行是吗

**Comment by yutchina** [comment]
从这里下载https://github.com/facebookresearch/mae

**Comment by LuoWeiCoder** [comment]
感谢作者

**Comment by LuoWeiCoder** [comment]
如果我下载mae模型，要放到pretrained_model下吗？

**Comment by yutchina** [comment]
不需要的 放在根目录即可

**Comment by LuoWeiCoder** [comment]
作者您好！我在复现您的工作之后，我设置的训练epoch是50，但是每次我训练完8轮后就自己停止了，然后会出现如下图所示的结果，这是为什么？然后还有就是最后输出的综合的准确率是不是自己手动去算的呀，我看没有打印出来。不好意思多次打扰您了！
![Uploading 1732880056059.jpg…]()

**Comment by LuoWeiCoder** [comment]
作者您好！我在复现您的工作之后，我设置的训练epoch是50，但是每次我训练完8轮后就自己停止了，然后会出现如下图所示的结果，这是为什么？然后还有就是最后输出的综合的准确率是不是自己手动去算的呀，我看没有打印出来。不好意思多次打扰您了！
![Uploading 1732880056059.jpg…]()

**Comment by yutchina** [comment]
你好 这个是因为设置了早停 你可以把早停删了 综合的结果在后面 你可以往后面拖一下 然后这个图片我好像看不见

**Comment by LuoWeiCoder** [comment]
![Uploading 1732880056059.jpg…]()

**Comment by LuoWeiCoder** [comment]
> 你好这是因为设置了早停你可以把早停删掉综合的结果在后面你可以往后面拖一下然后这个图片我好像看不见
早停机制是为了防止过拟合吗？我看您在论文中提到训练了50个以上的epoch，我在这里8个epoch就能达到很好的性能了吗？那我这样的实验算不算此成功呢？
![Uploading 1732880056059.jpg…]()

**Comment by yutchina** [comment]
你好，这个图片我好像看不见。早停是为了防止过拟合。
