### ISSUE TITLE
数据集咨询

### ISSUE THREAD

**Issue by Scientist888-star** [yutchina/MMDFND#6]

**Comment by yutchina** [comment]
你好，weibo的多领域数据已经处理好了，你可以直接通过readme的链接下载，weibo21的数据集你可以给我一个邮箱，我单独发你。

**Comment by Andrew-gx** [comment]
好的谢谢，我的邮箱是：wuhongbing@nudt.edu.cn

非常感谢！

**Comment by LuoWeiCoder** [comment]
作者您好，我也想要一份微博21的数据集可以吗？之前做了南博士的问卷调查一直没有回复，我的邮箱是：lw15630185926@gmail.com

**Comment by zkx990429** [comment]
作者你好，我也想要一份微博21的数据集可以吗？之前我做了南博士的问卷调查，一直没有回复。我一定会遵守南博士的协议，并在之后引用南博士的论文。我的邮箱是1277767811@qq.com

**Comment by BIGUOX** [comment]
作者你好，我也想要一份微博21的数据集可以吗？之前我做了南博士的问卷调查，一直没有回复。我一定会遵守南博士的协议，并在之后引用南博士的论文。我的邮箱是2398456592@qq.com. 非常感谢

**Comment by jdhhh521** [comment]
> 你好，weibo的多领域数据已经处理好了，你可以直接通过readme的链接下载，weibo21的数据集你可以给我一个邮箱，我单独发你。
作者您好，我也想要一份微博21的数据集可以吗？之前我做了南博士的问卷调查，一直没有回复。我一定会遵守南博士的协议，并在之后引用南博士的论文。我的邮箱是1134223857@qq.com 。非常感谢

**Comment by guowenjing02-code** [comment]
> 你好，weibo的多领域数据已经处理好了，你可以直接通过readme的链接下载，weibo21的数据集你可以给我一个邮箱，我单独发你。

作者您好，我也想要一份微博21的数据集可以吗？之前我做了南博士的问卷调查，一直没有回复。我一定会遵守南博士的协议，并在之后引用南博士的论文。我的邮箱是1607635251@qq.com。非常感谢
