### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by LuoWeiCoder** [yutchina/MMDFND#7]
作者您好，我也想要一份微博21的数据集可以吗？之前做了南博士的问卷调查一直没有回复，我的邮箱是：lw15630185926@gmail.com
麻烦您了作者，谢谢！

**Comment by sugarcandy** [comment]
作者您好，我也想要一份微博21的数据集可以吗？给南博士发邮箱没回复，我的邮箱是：yuchao@stu.cqu.edu.cn
麻烦您了，谢谢！
